# Задание на повторение материала**

In [1]:
import numpy as np

### Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)

In [3]:
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


### Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [4]:
a1 = a.reshape((2, 6))
a2 = a.reshape((3, 4))
a3 = a.reshape((4, 3))
a4 = a.reshape((6, 2))
a5 = a.reshape((12, 1))

In [5]:
print('a1:')
print(a1)
print('a2:')
print(a2)
print('a3:')
print(a3)
print('a4:')
print(a4)
print('a5:')
print(a5)

a1:
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
a2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
a3:
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
a4:
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
a5:
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк)

In [6]:
b1 = a.reshape((2, -1))
b2 = a.reshape((3, -1))
b3 = a.reshape((4, -1))
b4 = a.reshape((-1, 2))
b5 = a.reshape((-1, 1))

In [7]:
print('b1:')
print(b1)
print('b2:')
print(b2)
print('b3:')
print(b3)
print('b4:')
print(b4)
print('b5:')
print(b5)

b1:
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
b2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
b3:
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
b4:
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
b5:
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: нельзя, так как для обращения к ячейки нужно 2 индекса (строка, столбец), да и ndim покажет, что размерность равна 2

In [8]:
a5[11, 0]

23

In [9]:
a5.ndim

2

### Задание 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [10]:
a5 = np.random.randn(3, 4)
print(a5)

[[-0.92497675 -0.95162579 -1.16289453  0.61899638]
 [ 0.27189442  0.7450852  -0.23485553 -0.77001911]
 [ 0.04838687  0.92941159  0.14739213 -0.71248169]]


In [11]:
b5 = a5.flatten()
print(b5)

[-0.92497675 -0.95162579 -1.16289453  0.61899638  0.27189442  0.7450852
 -0.23485553 -0.77001911  0.04838687  0.92941159  0.14739213 -0.71248169]


In [12]:
a5.size == b5.size

True

### Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [13]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


### Задание 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [14]:
b = np.arange(20, 1, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [15]:
print('Массивы {}'.format('равны' if np.array_equal(a, b) else 'НЕ равны'))

Массивы равны


#### Ответ: Массивы не отличаются

### Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [16]:
a = np.zeros((2, 2))
print('Массив a:', a, sep='\n')
b = np.ones((3, 2))
print('Массив a:', b, sep='\n')

Массив a:
[[0. 0.]
 [0. 0.]]
Массив a:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
v = np.concatenate((a, b), axis = 0)
print('Массив v:', v, sep='\n')
print()
print('v.size = {}'.format(v.size))

Массив v:
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

v.size = 10


### Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [21]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [23]:
A = a.reshape((4,-1))
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [28]:
B = A.dot(At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [31]:
print('Размерность матрицы B = {}'.format(B.shape))

Размерность матрицы B = (4, 4)


In [34]:
d = np.linalg.det(B)
print('Определитель матрицы B = {}'.format(d))

Определитель матрицы B = 0.0


#### Ответ: для матрицы B не получится получить обратную, так как определитель равен 0

### Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [36]:
np.random.seed(42)

### Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [41]:
c = np.random.randint(0, 16, (16))
print(c)

[14 10  7 12  4  6  9  2  6 10 10  7  4  3  7  7]


### Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [42]:
C = c.reshape(4, -1)
print(C)

[[14 10  7 12]
 [ 4  6  9  2]
 [ 6 10 10  7]
 [ 4  3  7  7]]


In [48]:
D = C + B
print('Матрица D:', D, sep='\n')

Матрица D:
[[ 19  24  30  44]
 [ 18  56  95 124]
 [ 29  96 159 219]
 [ 36 125 219 309]]


In [50]:
d_D = np.linalg.det(D)
print(f'Определитель матрицы D = {d_D}')

Определитель матрицы D = -111673.00000000003


In [51]:
r_D = np.linalg.matrix_rank(D)
print(f'Ранк матрицы D = {r_D}')

Ранк матрицы D = 4


In [52]:
D_inv = np.linalg.inv(D)
print('Матрица обратная к D:', D_inv, sep='\n')

Матрица обратная к D:
[[ 0.08470266  0.0892427  -0.14123378  0.0522239 ]
 [-0.03140419 -0.15677917  0.28484056 -0.13449088]
 [-0.01653041  0.22457532 -0.16315493  0.02786708]
 [ 0.01455141 -0.10614025  0.01686173  0.03180715]]


Проверка

In [53]:
m = D.dot(D_inv)
print(m)

[[ 1.00000000e+00  1.77635684e-15 -1.77635684e-15 -6.66133815e-16]
 [-1.24900090e-16  1.00000000e+00  0.00000000e+00 -8.88178420e-16]
 [ 1.94289029e-16  0.00000000e+00  1.00000000e+00 -8.88178420e-16]
 [-1.11022302e-16  0.00000000e+00  7.10542736e-15  1.00000000e+00]]


### Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [55]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1

In [56]:
print('Матрица D_inv:', D_inv, sep='\n')
print('Матрица B:', B, sep='\n')
print('Матрица C:', C, sep='\n')

Матрица D_inv:
[[1. 1. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 1.]]
Матрица B:
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица C:
[[14 10  7 12]
 [ 4  6  9  2]
 [ 6 10 10  7]
 [ 4  3  7  7]]


In [57]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14   7  32]
 [  4   6  86   2]
 [  6  86  10 212]
 [ 32   3 212 302]]
